# Generated by Django 3.2.13 on 2023-11-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ozluk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=10)),
                ('ad', models.CharField(max_length=15)),
                ('soyad', models.CharField(max_length=15)),
                ('bolum', models.CharField(default='Hukuk Fakültesi', max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='Universite',
        ),
    ]
