# Generated by Django 3.2.13 on 2023-11-20 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0002_auto_20231117_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='UyeBilgileri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cepTelefonu', models.IntegerField()),
                ('uye', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='universite.ozluk')),
            ],
        ),
    ]
