# Generated by Django 3.2.13 on 2023-11-25 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0003_uyebilgileri'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uyebilgileri',
            name='uye',
        ),
        migrations.DeleteModel(
            name='Ozluk',
        ),
        migrations.DeleteModel(
            name='UyeBilgileri',
        ),
    ]
