# Generated by Django 3.2.13 on 2023-11-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universite', '0004_auto_20231125_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolum_no', models.CharField(max_length=15)),
                ('bolum_ad', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Fakulte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fakulte_no', models.CharField(max_length=15)),
                ('fakulte_ad', models.CharField(max_length=15)),
            ],
        ),
    ]
