# Generated by Django 3.2.13 on 2023-11-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0005_bolum_fakulte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolum',
            name='bolum_ad',
            field=models.CharField(max_length=35),
        ),
    ]
