# Generated by Django 3.2.13 on 2023-11-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0006_alter_bolum_bolum_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolum',
            name='bolum_ad',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fakulte',
            name='fakulte_ad',
            field=models.CharField(max_length=50),
        ),
    ]
