# Generated by Django 3.2.13 on 2023-11-27 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0007_auto_20231126_1342'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bolum',
        ),
        migrations.DeleteModel(
            name='Fakulte',
        ),
    ]
