# Generated by Django 3.2.13 on 2023-11-27 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universite', '0008_auto_20231127_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fakulte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fakulte_no', models.CharField(max_length=15)),
                ('fakulte_ad', models.CharField(default='fakülte', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Bolum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolum_no', models.CharField(max_length=15)),
                ('bolum_ad', models.CharField(max_length=50)),
                ('fakulte_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolumu', to='universite.fakulte')),
            ],
        ),
    ]
