# Generated by Django 3.2.13 on 2023-11-27 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0009_bolum_fakulte'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bolum',
        ),
        migrations.DeleteModel(
            name='Fakulte',
        ),
    ]
