# Generated by Django 3.2.13 on 2023-12-07 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0012_alter_fakulte_fakulte_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolum',
            name='fakulte',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='universite.fakulte'),
        ),
    ]
