# Generated by Django 3.2.13 on 2023-12-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0013_bolum_fakulte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolum',
            name='bolum_no',
            field=models.IntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='fakulte',
            name='fakulte_no',
            field=models.IntegerField(max_length=15),
        ),
    ]
