# Generated by Django 3.2.13 on 2023-12-10 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0014_auto_20231210_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bolum',
            name='bolum_no',
        ),
        migrations.RemoveField(
            model_name='fakulte',
            name='fakulte_no',
        ),
    ]
