# Generated by Django 3.2.13 on 2023-12-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0015_auto_20231210_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolum',
            name='bolum_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fakulte',
            name='fakulte_no',
            field=models.IntegerField(default=0),
        ),
    ]
