# Generated by Django 3.2.13 on 2023-12-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0016_auto_20231211_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bolum',
            old_name='fakulte',
            new_name='fakulte_ad',
        ),
        migrations.AlterField(
            model_name='fakulte',
            name='fakulte_ad',
            field=models.CharField(default='fakulte_ad', max_length=50),
        ),
    ]
