# Generated by Django 3.2.13 on 2023-12-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0017_auto_20231211_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bolum',
            old_name='fakulte_ad',
            new_name='fakulte',
        ),
        migrations.AlterField(
            model_name='fakulte',
            name='fakulte_ad',
            field=models.CharField(default='fakulte', max_length=50),
        ),
    ]
