# Generated by Django 3.2.13 on 2023-12-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0018_auto_20231211_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolum',
            name='bolum_adres',
            field=models.CharField(default='bolum_adres', max_length=100),
        ),
        migrations.AddField(
            model_name='bolum',
            name='bolum_ciftyan',
            field=models.CharField(default='bolum_ciftyan', max_length=400),
        ),
        migrations.AddField(
            model_name='bolum',
            name='bolum_dekan',
            field=models.CharField(default='bolum_dekan', max_length=50),
        ),
        migrations.AddField(
            model_name='bolum',
            name='bolum_erasmus',
            field=models.CharField(default='bolum_erasmus', max_length=400),
        ),
        migrations.AddField(
            model_name='bolum',
            name='bolum_fırsat',
            field=models.CharField(default='bolum_fırsat', max_length=400),
        ),
        migrations.AddField(
            model_name='bolum',
            name='bolum_logo',
            field=models.CharField(default='bolum_logo', max_length=50),
        ),
        migrations.AddField(
            model_name='bolum',
            name='bolum_mail',
            field=models.CharField(default='bolum_mail', max_length=50),
        ),
        migrations.AddField(
            model_name='bolum',
            name='bolum_mezun',
            field=models.CharField(default='bolum_mezun', max_length=400),
        ),
        migrations.AddField(
            model_name='bolum',
            name='bolum_profil',
            field=models.CharField(default='bolum_profil', max_length=400),
        ),
        migrations.AddField(
            model_name='bolum',
            name='bolum_staj',
            field=models.CharField(default='bolum_staj', max_length=400),
        ),
        migrations.AddField(
            model_name='bolum',
            name='bolum_tel',
            field=models.CharField(default='bolum_tel', max_length=50),
        ),
        migrations.AddField(
            model_name='bolum',
            name='bolum_url',
            field=models.CharField(default='bolum_url', max_length=200),
        ),
        migrations.AddField(
            model_name='fakulte',
            name='fakulte_adres',
            field=models.CharField(default='fakulte_adres', max_length=100),
        ),
        migrations.AddField(
            model_name='fakulte',
            name='fakulte_dekan',
            field=models.CharField(default='fakulte_dekan', max_length=50),
        ),
        migrations.AddField(
            model_name='fakulte',
            name='fakulte_kampus',
            field=models.CharField(default='fakulte_kampus', max_length=50),
        ),
        migrations.AddField(
            model_name='fakulte',
            name='fakulte_logo',
            field=models.CharField(default='fakulte_logo', max_length=50),
        ),
        migrations.AddField(
            model_name='fakulte',
            name='fakulte_mail',
            field=models.CharField(default='fakulte_mail', max_length=50),
        ),
        migrations.AddField(
            model_name='fakulte',
            name='fakulte_tel',
            field=models.CharField(default='fakulte_tel', max_length=50),
        ),
        migrations.AddField(
            model_name='fakulte',
            name='fakulte_url',
            field=models.CharField(default='fakulte_url', max_length=200),
        ),
        migrations.AlterField(
            model_name='bolum',
            name='bolum_ad',
            field=models.CharField(default='bolum_ad', max_length=50),
        ),
        migrations.AlterField(
            model_name='fakulte',
            name='fakulte_ad',
            field=models.CharField(default='fakulte_ad', max_length=50),
        ),
    ]
