# Generated by Django 3.2.13 on 2023-12-15 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0019_auto_20231215_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kampus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kampus', models.CharField(default='kampus', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='fakulte',
            name='fakulte_kampus',
        ),
        migrations.AlterField(
            model_name='bolum',
            name='bolum_ciftyan',
            field=models.TextField(default='bolum_ciftyan', max_length=400),
        ),
        migrations.AlterField(
            model_name='bolum',
            name='bolum_erasmus',
            field=models.TextField(default='bolum_erasmus', max_length=400),
        ),
        migrations.AlterField(
            model_name='bolum',
            name='bolum_fırsat',
            field=models.TextField(default='bolum_fırsat', max_length=400),
        ),
        migrations.AlterField(
            model_name='bolum',
            name='bolum_mezun',
            field=models.TextField(default='bolum_mezun', max_length=400),
        ),
        migrations.AlterField(
            model_name='bolum',
            name='bolum_profil',
            field=models.TextField(default='bolum_profil', max_length=400),
        ),
        migrations.AlterField(
            model_name='bolum',
            name='bolum_staj',
            field=models.TextField(default='bolum_staj', max_length=400),
        ),
        migrations.AlterField(
            model_name='fakulte',
            name='fakulte_adres',
            field=models.TextField(default='fakulte_adres', max_length=100),
        ),
        migrations.AddField(
            model_name='fakulte',
            name='kampus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='universite.kampus'),
        ),
    ]
