# Generated by Django 3.2.13 on 2023-12-15 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0020_auto_20231215_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='anasayfa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haber1', models.CharField(max_length=200)),
                ('haber2', models.CharField(max_length=200)),
                ('haber3', models.CharField(max_length=200)),
                ('haber4', models.CharField(max_length=200)),
                ('tarih1', models.DateTimeField()),
                ('tarih2', models.DateTimeField()),
                ('tarih3', models.DateTimeField()),
                ('tarih4', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='bolum',
            name='fakulte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universite.fakulte'),
        ),
        migrations.AlterField(
            model_name='fakulte',
            name='kampus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universite.kampus'),
        ),
    ]
