# Generated by Django 3.2.13 on 2023-12-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0021_auto_20231215_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kampus',
            name='kampus',
        ),
        migrations.AddField(
            model_name='kampus',
            name='kampus_adi',
            field=models.CharField(default='kampus_adi', max_length=50),
        ),
        migrations.AddField(
            model_name='kampus',
            name='kampus_adres',
            field=models.CharField(default='kampus_adres', max_length=50),
        ),
        migrations.RemoveField(
            model_name='fakulte',
            name='kampus',
        ),
        migrations.AddField(
            model_name='fakulte',
            name='kampus',
            field=models.ManyToManyField(related_name='adresler', to='universite.Kampus'),
        ),
    ]
