# Generated by Django 3.2.13 on 2023-12-16 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0022_auto_20231216_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolum',
            name='fakulte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolumler', to='universite.fakulte'),
        ),
        migrations.AlterField(
            model_name='fakulte',
            name='kampus',
            field=models.ManyToManyField(related_name='fakulteler', to='universite.Kampus'),
        ),
    ]
