# Generated by Django 3.2.13 on 2023-12-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0023_auto_20231216_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fakulte',
            old_name='kampus',
            new_name='kampusler',
        ),
        migrations.AlterField(
            model_name='kampus',
            name='kampus_adres',
            field=models.CharField(default='kampus_adres', max_length=100),
        ),
    ]
