# Generated by Django 3.2.13 on 2023-12-16 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0024_auto_20231216_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fakulte',
            name='kampusler',
        ),
        migrations.AddField(
            model_name='fakulte',
            name='kampus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fakulteler', to='universite.kampus'),
        ),
        migrations.AlterField(
            model_name='bolum',
            name='fakulte',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bolumler', to='universite.fakulte'),
        ),
    ]
