# Generated by Django 3.2.13 on 2023-12-16 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0025_auto_20231216_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fakulte',
            name='fakulte_adres',
        ),
    ]
