# Generated by Django 3.2.13 on 2023-12-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0027_auto_20231222_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolum',
            name='kisaltma',
            field=models.TextField(default='ttt', max_length=5),
        ),
        migrations.AddField(
            model_name='fakulte',
            name='kisaltma',
            field=models.TextField(default='ttt', max_length=5),
        ),
    ]
