# Generated by Django 3.2.13 on 2024-01-04 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0030_auto_20231230_0215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anasayfa',
            old_name='haber1',
            new_name='haber',
        ),
        migrations.RenameField(
            model_name='anasayfa',
            old_name='tarih1',
            new_name='tarih',
        ),
        migrations.RemoveField(
            model_name='anasayfa',
            name='haber2',
        ),
        migrations.RemoveField(
            model_name='anasayfa',
            name='haber3',
        ),
        migrations.RemoveField(
            model_name='anasayfa',
            name='haber4',
        ),
        migrations.RemoveField(
            model_name='anasayfa',
            name='tarih2',
        ),
        migrations.RemoveField(
            model_name='anasayfa',
            name='tarih3',
        ),
        migrations.RemoveField(
            model_name='anasayfa',
            name='tarih4',
        ),
    ]
