# Generated by Django 3.2.13 on 2024-01-04 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0031_auto_20240104_1937'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='anasayfa',
            new_name='Haberler',
        ),
    ]
