# Generated by Django 3.2.13 on 2024-01-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0032_rename_anasayfa_haberler'),
    ]

    operations = [
        migrations.AddField(
            model_name='haberler',
            name='haber_baslik',
            field=models.CharField(default='haber_baslik', max_length=50),
        ),
        migrations.AlterField(
            model_name='haberler',
            name='haber',
            field=models.CharField(default='haber', max_length=200),
        ),
    ]
