# Generated by Django 3.2.13 on 2024-01-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0033_auto_20240106_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='haberler',
            name='haber_kisaltma',
            field=models.CharField(default='haber_kisaltma', max_length=20),
        ),
    ]
