# Generated by Django 3.2.13 on 2024-01-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0034_haberler_haber_kisaltma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haberler',
            name='haber',
            field=models.TextField(default='haber', max_length=400),
        ),
    ]
