# Generated by Django 3.2.13 on 2024-01-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0035_alter_haberler_haber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haberler',
            name='tarih',
            field=models.DateField(),
        ),
    ]
