# Generated by Django 3.2.13 on 2024-01-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0036_alter_haberler_tarih'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haberler',
            name='tarih',
            field=models.DateTimeField(),
        ),
    ]
